"""Generates crates/decoder/src/native_tables.rs from upstream error enums.

    python3 scripts/gen_native_tables.py ~/.cargo/registry/src/index.crates.io-*/ \
        > crates/decoder/src/native_tables.rs

The listed crate versions must be present in the cargo registry cache.
"""
import re, sys
def parse(path, enum):
    src = open(path).read()
    body = re.search(r"pub enum " + enum + r"\s*\{(.*?)\n\}", src, re.S).group(1)
    out, msg, doc, n = [], None, [], 0
    # join multi-line #[error(...)] attributes
    # collapse every #[error("...")] onto one line, including multi-line literals
    body = re.sub(r'#\[(?:error|msg)\(\s*"(.*?)"\s*,?\s*\)\]',
                  lambda m: '#[error("' + re.sub(r"\s+", " ", m.group(1)) + '")]', body, flags=re.S)
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("///"): doc.append(s[3:].strip()); continue
        m = re.match(r'#\[error\("(.*)"\)\]', s)
        if m: msg = m.group(1); continue
        m = re.match(r"([A-Z][A-Za-z0-9]*)\s*(?:=\s*(\d+))?\s*,", s)
        if m:
            if m.group(2): n = int(m.group(2))
            text = msg if msg is not None else " ".join(doc).rstrip(".")
            out.append((n, m.group(1), text)); n += 1; msg, doc = None, []
        elif s and not s.startswith("//") and not s.startswith("#"): doc = []
    return out
def emit(name, rows):
    print(f"pub(crate) const {name}: &[(u32, &str, &str)] = &[")
    for n, v, t in rows:
        t = t.replace("\\", "\\\\").replace('"', '\\"')
        print(f'    ({n}, "{v}", "{t}"),')
    print("];\n")
R = sys.argv[1]
print("// @generated by a script from upstream error enums; do not edit by hand.")
print("// Sources (crates.io):")
print("//   solana-system-interface 3.3.0 src/error.rs  SystemError")
print("//   spl-token-interface 3.0.0 src/error.rs      TokenError")
print("//   spl-token-2022-interface 3.1.2 src/error.rs TokenError")
print("//   spl-associated-token-account 8.0.0 src/error.rs AssociatedTokenAccountError")
print("//   anchor-lang-error 1.2.1 src/lib.rs          ErrorCode (Anchor framework errors)")
print("// Entries: (code, name, message).\n")
emit("SYSTEM", parse(R+"/solana-system-interface-3.3.0/src/error.rs", "SystemError"))
emit("TOKEN", parse(R+"/spl-token-interface-3.0.0/src/error.rs", "TokenError"))
emit("TOKEN_2022", parse(R+"/spl-token-2022-interface-3.1.2/src/error.rs", "TokenError"))
emit("ASSOCIATED_TOKEN", parse(R+"/spl-associated-token-account-8.0.0/src/error.rs", "AssociatedTokenAccountError"))
emit("ANCHOR_FRAMEWORK", parse(R+"/anchor-lang-error-1.2.1/src/lib.rs", "ErrorCode"))
