// @generated by a script from upstream error enums; do not edit by hand.
// Sources (crates.io):
//   solana-system-interface 3.3.0 src/error.rs  SystemError
//   spl-token-interface 3.0.0 src/error.rs      TokenError
//   spl-token-2022-interface 3.1.2 src/error.rs TokenError
//   spl-associated-token-account 8.0.0 src/error.rs AssociatedTokenAccountError
//   anchor-lang-error 1.2.1 src/lib.rs          ErrorCode (Anchor framework errors)
// Entries: (code, name, message).

pub(crate) const SYSTEM: &[(u32, &str, &str)] = &[
    (
        0,
        "AccountAlreadyInUse",
        "An account with the same address already exists",
    ),
    (
        1,
        "ResultWithNegativeLamports",
        "Account does not have enough SOL to perform the operation",
    ),
    (
        2,
        "InvalidProgramId",
        "Cannot assign account to this program id",
    ),
    (
        3,
        "InvalidAccountDataLength",
        "Cannot allocate account data of this length",
    ),
    (
        4,
        "MaxSeedLengthExceeded",
        "Length of requested seed is too long",
    ),
    (
        5,
        "AddressWithSeedMismatch",
        "Provided address does not match addressed derived from seed",
    ),
    (
        6,
        "NonceNoRecentBlockhashes",
        "Advancing stored nonce requires a populated RecentBlockhashes sysvar",
    ),
    (
        7,
        "NonceBlockhashNotExpired",
        "Stored nonce is still in recent_blockhashes",
    ),
    (
        8,
        "NonceUnexpectedBlockhashValue",
        "Specified nonce does not match stored nonce",
    ),
];

pub(crate) const TOKEN: &[(u32, &str, &str)] = &[
    (
        0,
        "NotRentExempt",
        "Lamport balance below rent-exempt threshold",
    ),
    (1, "InsufficientFunds", "Insufficient funds"),
    (2, "InvalidMint", "Invalid Mint"),
    (3, "MintMismatch", "Account not associated with this Mint"),
    (4, "OwnerMismatch", "Owner does not match"),
    (5, "FixedSupply", "Fixed supply"),
    (6, "AlreadyInUse", "Already in use"),
    (
        7,
        "InvalidNumberOfProvidedSigners",
        "Invalid number of provided signers",
    ),
    (
        8,
        "InvalidNumberOfRequiredSigners",
        "Invalid number of required signers",
    ),
    (9, "UninitializedState", "State is uninitialized"),
    (
        10,
        "NativeNotSupported",
        "Instruction does not support native tokens",
    ),
    (
        11,
        "NonNativeHasBalance",
        "Non-native account can only be closed if its balance is zero",
    ),
    (12, "InvalidInstruction", "Invalid instruction"),
    (
        13,
        "InvalidState",
        "State is invalid for requested operation",
    ),
    (14, "Overflow", "Operation overflowed"),
    (
        15,
        "AuthorityTypeNotSupported",
        "Account does not support specified authority type",
    ),
    (
        16,
        "MintCannotFreeze",
        "This token mint cannot freeze accounts",
    ),
    (17, "AccountFrozen", "Account is frozen"),
    (
        18,
        "MintDecimalsMismatch",
        "The provided decimals value different from the Mint decimals",
    ),
    (
        19,
        "NonNativeNotSupported",
        "Instruction does not support non-native tokens",
    ),
];

pub(crate) const TOKEN_2022: &[(u32, &str, &str)] = &[
    (0, "NotRentExempt", "Lamport balance below rent-exempt threshold"),
    (1, "InsufficientFunds", "Insufficient funds"),
    (2, "InvalidMint", "Invalid Mint"),
    (3, "MintMismatch", "Account not associated with this Mint"),
    (4, "OwnerMismatch", "Owner does not match"),
    (5, "FixedSupply", "Fixed supply"),
    (6, "AlreadyInUse", "Already in use"),
    (7, "InvalidNumberOfProvidedSigners", "Invalid number of provided signers"),
    (8, "InvalidNumberOfRequiredSigners", "Invalid number of required signers"),
    (9, "UninitializedState", "State is uninitialized"),
    (10, "NativeNotSupported", "Instruction does not support native tokens"),
    (11, "NonNativeHasBalance", "Non-native account can only be closed if its balance is zero"),
    (12, "InvalidInstruction", "Invalid instruction"),
    (13, "InvalidState", "State is invalid for requested operation"),
    (14, "Overflow", "Operation overflowed"),
    (15, "AuthorityTypeNotSupported", "Account does not support specified authority type"),
    (16, "MintCannotFreeze", "This token mint cannot freeze accounts"),
    (17, "AccountFrozen", "Account is frozen"),
    (18, "MintDecimalsMismatch", "The provided decimals value different from the Mint decimals"),
    (19, "NonNativeNotSupported", "Instruction does not support non-native tokens"),
    (20, "ExtensionTypeMismatch", "Extension type does not match already existing extensions"),
    (21, "ExtensionBaseMismatch", "Extension does not match the base type provided"),
    (22, "ExtensionAlreadyInitialized", "Extension already initialized on this account"),
    (23, "ConfidentialTransferAccountHasBalance", "An account can only be closed if its confidential balance is zero"),
    (24, "ConfidentialTransferAccountNotApproved", "Account not approved for confidential transfers"),
    (25, "ConfidentialTransferDepositsAndTransfersDisabled", "Account not accepting deposits or transfers"),
    (26, "ConfidentialTransferElGamalPubkeyMismatch", "ElGamal public key mismatch"),
    (27, "ConfidentialTransferBalanceMismatch", "Balance mismatch"),
    (28, "MintHasSupply", "Mint has non-zero supply. Burn all tokens before closing the mint"),
    (29, "NoAuthorityExists", "No authority exists to perform the desired operation"),
    (30, "TransferFeeExceedsMaximum", "Transfer fee exceeds maximum of 10,000 basis points"),
    (31, "MintRequiredForTransfer", "Mint required for this account to transfer tokens, use `transfer_checked` or `transfer_checked_with_fee`"),
    (32, "FeeMismatch", "Calculated fee does not match expected fee"),
    (33, "FeeParametersMismatch", "Fee parameters associated with zero-knowledge proofs do not match fee parameters in mint"),
    (34, "ImmutableOwner", "The owner authority cannot be changed"),
    (35, "AccountHasWithheldTransferFees", "An account can only be closed if its withheld fee balance is zero, harvest fees to the mint and try again"),
    (36, "NoMemo", "No memo in previous instruction; required for recipient to receive a transfer"),
    (37, "NonTransferable", "Transfer is disabled for this mint"),
    (38, "NonTransferableNeedsImmutableOwnership", "Non-transferable tokens can't be minted to an account without immutable ownership"),
    (39, "MaximumPendingBalanceCreditCounterExceeded", "The total number of `Deposit` and `Transfer` instructions to an account cannot exceed the associated `maximum_pending_balance_credit_counter`"),
    (40, "MaximumDepositAmountExceeded", "Deposit amount exceeds maximum limit"),
    (41, "CpiGuardSettingsLocked", "CPI Guard cannot be enabled or disabled in CPI"),
    (42, "CpiGuardTransferBlocked", "CPI Guard is enabled, and a program attempted to transfer user funds via CPI without using a delegate"),
    (43, "CpiGuardBurnBlocked", "CPI Guard is enabled, and a program attempted to burn user funds via CPI without using a delegate"),
    (44, "CpiGuardCloseAccountBlocked", "CPI Guard is enabled, and a program attempted to close an account via CPI without returning lamports to owner"),
    (45, "CpiGuardApproveBlocked", "CPI Guard is enabled, and a program attempted to approve a delegate via CPI"),
    (46, "CpiGuardSetAuthorityBlocked", "CPI Guard is enabled, and a program attempted to add or replace an authority via CPI"),
    (47, "CpiGuardOwnerChangeBlocked", "Account ownership cannot be changed while CPI Guard is enabled"),
    (48, "ExtensionNotFound", "Extension not found in account data"),
    (49, "NonConfidentialTransfersDisabled", "Non-confidential transfers disabled"),
    (50, "ConfidentialTransferFeeAccountHasWithheldFee", "An account can only be closed if the confidential withheld fee is zero"),
    (51, "InvalidExtensionCombination", "A mint or an account is initialized to an invalid combination of extensions"),
    (52, "InvalidLengthForAlloc", "Extension allocation with overwrite must use the same length"),
    (53, "AccountDecryption", "Failed to decrypt a confidential transfer account"),
    (54, "ProofGeneration", "Failed to generate proof"),
    (55, "InvalidProofInstructionOffset", "An invalid proof instruction offset was provided"),
    (56, "HarvestToMintDisabled", "Harvest of withheld tokens to mint is disabled"),
    (57, "SplitProofContextStateAccountsNotSupported", "Split proof context state accounts not supported for instruction"),
    (58, "NotEnoughProofContextStateAccounts", "Not enough proof context state accounts provided"),
    (59, "MalformedCiphertext", "Ciphertext is malformed"),
    (60, "CiphertextArithmeticFailed", "Ciphertext arithmetic failed"),
    (61, "PedersenCommitmentMismatch", "Pedersen commitment mismatch"),
    (62, "RangeProofLengthMismatch", "Range proof length mismatch"),
    (63, "IllegalBitLength", "Illegal transfer amount bit length"),
    (64, "FeeCalculation", "Fee calculation failed"),
    (65, "IllegalMintBurnConversion", "Withdraw / Deposit not allowed for confidential-mint-burn"),
    (66, "InvalidScale", "Invalid scale for scaled ui amount"),
    (67, "MintPaused", "Transferring, minting, and burning is paused on this mint"),
    (68, "PendingBalanceNonZero", "Key rotation attempted while pending balance is not zero"),
];

pub(crate) const ASSOCIATED_TOKEN: &[(u32, &str, &str)] = &[(
    0,
    "InvalidOwner",
    "Associated token account owner does not match address derivation",
)];

pub(crate) const ANCHOR_FRAMEWORK: &[(u32, &str, &str)] = &[
    (
        100,
        "InstructionMissing",
        "Instruction discriminator not provided",
    ),
    (
        101,
        "InstructionFallbackNotFound",
        "Fallback functions are not supported",
    ),
    (
        102,
        "InstructionDidNotDeserialize",
        "The program could not deserialize the given instruction",
    ),
    (
        103,
        "InstructionDidNotSerialize",
        "The program could not serialize the given instruction",
    ),
    (
        1000,
        "IdlInstructionStub",
        "The program was compiled without idl instructions",
    ),
    (
        1001,
        "IdlInstructionInvalidProgram",
        "Invalid program given to the IDL instruction",
    ),
    (
        1002,
        "IdlAccountNotEmpty",
        "IDL account must be empty in order to resize, try closing first",
    ),
    (
        1500,
        "EventInstructionStub",
        "The program was compiled without `event-cpi` feature",
    ),
    (2000, "ConstraintMut", "A mut constraint was violated"),
    (
        2001,
        "ConstraintHasOne",
        "A has one constraint was violated",
    ),
    (2002, "ConstraintSigner", "A signer constraint was violated"),
    (2003, "ConstraintRaw", "A raw constraint was violated"),
    (2004, "ConstraintOwner", "An owner constraint was violated"),
    (
        2005,
        "ConstraintRentExempt",
        "A rent exemption constraint was violated",
    ),
    (2006, "ConstraintSeeds", "A seeds constraint was violated"),
    (
        2007,
        "ConstraintExecutable",
        "An executable constraint was violated",
    ),
    (
        2008,
        "ConstraintState",
        "Deprecated Error, feel free to replace with something else",
    ),
    (
        2009,
        "ConstraintAssociated",
        "An associated constraint was violated",
    ),
    (
        2010,
        "ConstraintAssociatedInit",
        "An associated init constraint was violated",
    ),
    (2011, "ConstraintClose", "A close constraint was violated"),
    (
        2012,
        "ConstraintAddress",
        "An address constraint was violated",
    ),
    (2013, "ConstraintZero", "Expected zero account discriminant"),
    (
        2014,
        "ConstraintTokenMint",
        "A token mint constraint was violated",
    ),
    (
        2015,
        "ConstraintTokenOwner",
        "A token owner constraint was violated",
    ),
    (
        2016,
        "ConstraintMintMintAuthority",
        "A mint mint authority constraint was violated",
    ),
    (
        2017,
        "ConstraintMintFreezeAuthority",
        "A mint freeze authority constraint was violated",
    ),
    (
        2018,
        "ConstraintMintDecimals",
        "A mint decimals constraint was violated",
    ),
    (2019, "ConstraintSpace", "A space constraint was violated"),
    (
        2020,
        "ConstraintAccountIsNone",
        "A required account for the constraint is None",
    ),
    (
        2021,
        "ConstraintTokenTokenProgram",
        "A token account token program constraint was violated",
    ),
    (
        2022,
        "ConstraintMintTokenProgram",
        "A mint token program constraint was violated",
    ),
    (
        2023,
        "ConstraintAssociatedTokenTokenProgram",
        "An associated token account token program constraint was violated",
    ),
    (
        2024,
        "ConstraintMintGroupPointerExtension",
        "A group pointer extension constraint was violated",
    ),
    (
        2025,
        "ConstraintMintGroupPointerExtensionAuthority",
        "A group pointer extension authority constraint was violated",
    ),
    (
        2026,
        "ConstraintMintGroupPointerExtensionGroupAddress",
        "A group pointer extension group address constraint was violated",
    ),
    (
        2027,
        "ConstraintMintGroupMemberPointerExtension",
        "A group member pointer extension constraint was violated",
    ),
    (
        2028,
        "ConstraintMintGroupMemberPointerExtensionAuthority",
        "A group member pointer extension authority constraint was violated",
    ),
    (
        2029,
        "ConstraintMintGroupMemberPointerExtensionMemberAddress",
        "A group member pointer extension group address constraint was violated",
    ),
    (
        2030,
        "ConstraintMintMetadataPointerExtension",
        "A metadata pointer extension constraint was violated",
    ),
    (
        2031,
        "ConstraintMintMetadataPointerExtensionAuthority",
        "A metadata pointer extension authority constraint was violated",
    ),
    (
        2032,
        "ConstraintMintMetadataPointerExtensionMetadataAddress",
        "A metadata pointer extension metadata address constraint was violated",
    ),
    (
        2033,
        "ConstraintMintCloseAuthorityExtension",
        "A close authority constraint was violated",
    ),
    (
        2034,
        "ConstraintMintCloseAuthorityExtensionAuthority",
        "A close authority extension authority constraint was violated",
    ),
    (
        2035,
        "ConstraintMintPermanentDelegateExtension",
        "A permanent delegate extension constraint was violated",
    ),
    (
        2036,
        "ConstraintMintPermanentDelegateExtensionDelegate",
        "A permanent delegate extension delegate constraint was violated",
    ),
    (
        2037,
        "ConstraintMintTransferHookExtension",
        "A transfer hook extension constraint was violated",
    ),
    (
        2038,
        "ConstraintMintTransferHookExtensionAuthority",
        "A transfer hook extension authority constraint was violated",
    ),
    (
        2039,
        "ConstraintMintTransferHookExtensionProgramId",
        "A transfer hook extension transfer hook program id constraint was violated",
    ),
    (
        2040,
        "ConstraintDuplicateMutableAccount",
        "A duplicate mutable account constraint was violated",
    ),
    (
        2041,
        "AccountAlreadyMigrated",
        "Account is already migrated",
    ),
    (
        2042,
        "AccountNotMigrated",
        "Account must be migrated before exiting",
    ),
    (
        2043,
        "ConstraintMintPausableExtension",
        "A pausable extension constraint was violated",
    ),
    (
        2044,
        "ConstraintMintPausableAuthority",
        "A pausable extension authority constraint was violated",
    ),
    (2500, "RequireViolated", "A require expression was violated"),
    (
        2501,
        "RequireEqViolated",
        "A require_eq expression was violated",
    ),
    (
        2502,
        "RequireKeysEqViolated",
        "A require_keys_eq expression was violated",
    ),
    (
        2503,
        "RequireNeqViolated",
        "A require_neq expression was violated",
    ),
    (
        2504,
        "RequireKeysNeqViolated",
        "A require_keys_neq expression was violated",
    ),
    (
        2505,
        "RequireGtViolated",
        "A require_gt expression was violated",
    ),
    (
        2506,
        "RequireGteViolated",
        "A require_gte expression was violated",
    ),
    (
        3000,
        "AccountDiscriminatorAlreadySet",
        "The account discriminator was already set on this account",
    ),
    (
        3001,
        "AccountDiscriminatorNotFound",
        "No discriminator was found on the account",
    ),
    (
        3002,
        "AccountDiscriminatorMismatch",
        "Account discriminator did not match what was expected",
    ),
    (
        3003,
        "AccountDidNotDeserialize",
        "Failed to deserialize the account",
    ),
    (
        3004,
        "AccountDidNotSerialize",
        "Failed to serialize the account",
    ),
    (
        3005,
        "AccountNotEnoughKeys",
        "Not enough account keys given to the instruction",
    ),
    (
        3006,
        "AccountNotMutable",
        "The given account is not mutable",
    ),
    (
        3007,
        "AccountOwnedByWrongProgram",
        "The given account is owned by a different program than expected",
    ),
    (3008, "InvalidProgramId", "Program ID was not as expected"),
    (
        3009,
        "InvalidProgramExecutable",
        "Program account is not executable",
    ),
    (3010, "AccountNotSigner", "The given account did not sign"),
    (
        3011,
        "AccountNotSystemOwned",
        "The given account is not owned by the system program",
    ),
    (
        3012,
        "AccountNotInitialized",
        "The program expected this account to be already initialized",
    ),
    (
        3013,
        "AccountNotProgramData",
        "The given account is not a program data account",
    ),
    (
        3014,
        "AccountNotAssociatedTokenAccount",
        "The given account is not the associated token account",
    ),
    (
        3015,
        "AccountSysvarMismatch",
        "The given public key does not match the required sysvar",
    ),
    (
        3016,
        "AccountReallocExceedsLimit",
        "The account reallocation exceeds the MAX_PERMITTED_DATA_INCREASE limit",
    ),
    (
        3017,
        "AccountDuplicateReallocs",
        "The account was duplicated for more than one reallocation",
    ),
    (
        4100,
        "DeclaredProgramIdMismatch",
        "The declared program id does not match the actual program id",
    ),
    (
        4101,
        "TryingToInitPayerAsProgramAccount",
        "You cannot/should not initialize the payer account as a program account",
    ),
    (
        4102,
        "InvalidNumericConversion",
        "Error during numeric conversion",
    ),
    (
        5000,
        "Deprecated",
        "The API being used is deprecated and should no longer be used",
    ),
];
